name: Publish Maven Package

on:
  push:
    branches:
      - main # or your desired branch

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          server-id: github # this id is referenced in settings.xml
          settings-path: ${{ github.workspace }} # creates settings.xml in the root directory

      - name: Publish to GitHub Packages
        run: mvn deploy --settings $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
