name: Publish Maven Package

on:
  push:
    branches:
      - main  # Change this if you want a different branch

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Publish to GitHub Packages
        run: mvn deploy --settings $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

    # Optional: This will only run if the build fails
    if: ${{ failure() }}
    steps:
      - name: Upload Build Logs
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: target/
