name: Update Tag v1.0.4 on Commit

on:
  push:
    branches:
      - main

jobs:
  update-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git User
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update Tag v1.0.4 to Latest Commit
        run: |
          git tag -f v1.0.4
          git push --force https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git refs/tags/v1.0.4

      - name: Update GitHub Release (Optional)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.4
          name: Release v1.0.4
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
